app: cdn
config:
  flyCDN:
    backends:
      getting-started:
        type: origin
        origin: https://getting-started.edgeapp.net
        headers:
          host: getting-started.edgeapp.net
    rules:
    - actionType: rewrite
      backendKey: getting-started
      hostname: ""
      pathPattern: ""
      httpHeaderKey: ""
      pathMatchMode: "prefix"
      redirectStatus: 302
      httpHeaderValue: ""
      redirectURLPattern: ""
      responseReplacements: []
      pathReplacementPattern: ""
    middleware:
    - type: https-upgrader
