config: &config
  flyCDN:
    backends:
      fly:
        type: origin
        origin: https://fly.io/
        headers:
          host: fly.io
    rules:
    - actionType: rewrite
      backendKey: fly
    middleware:
    - type: https-upgrader
    - type: auto-webp

default: &default
  app: cdn
  config:
    <<: *config

development:
  <<: *default

test:
  <<: *default
  config:
    <<: *config
    aws_s3_access_key_id:
      fromSecret: aws_s3_access_key_id
    aws_s3_secret_access_key:
      fromSecret: aws_s3_secret_access_key

production:
  <<: *default
